### ISSUE TITLE
Full list of settings not available in plugin settings

### ISSUE THREAD

**Issue by ZOXSOCKS** [ruslanlap/PowerToysRun-VideoDownloader#5]
The only options I have to change in the plugin manager are as pictured below. I've re-installed the plugin, and restarted both Powertoys and my computer. I'm on the very latest version of powertoys (0.91.1) on Windows 10 LTSC.

Thanks: 

![Image](https://github.com/user-attachments/assets/73a5642c-e4ea-42ca-9a74-6a0408db8f94)

**Comment by ruslanlap** [comment]
Thanks for the detailed report and screenshot!

Tomorrow I’ll take a closer look at your request and try to reproduce the issue on my side to better understand what’s going on.
Sorry for the inconvenience, and thank you for your patience!

**Comment by ruslanlap** [comment]
Thank you for your feedback! I'm happy to inform you that the full list of settings is now available in the plugin settings in the new release v1.0.6. All settings fields have been converted to text fields for better compatibility with PowerToys settings panel. Please check out the release notes for more details: https://github.com/ruslanlap/PowerToysRun-VideoDownloader/releases/tag/v1.0.6

**Comment by ruslanlap** [comment]
Thank you for your feedback! I'm happy to inform you that the settings issue has been fixed in the new release v1.0.6. All settings are now properly saved and loaded. Please check out the release notes for more details: https://github.com/ruslanlap/PowerToysRun-VideoDownloader/releases/tag/v1.0.6

**Comment by ZOXSOCKS** [comment]
This update fixed the issue with not downloading, but even after updating (double triple checked!) the settings still don't appear in Powertoys! Also, the version still says 0.9 (and the link to the site doesn't go to anywhere) 

![Image](https://github.com/user-attachments/assets/01e1604b-c8dc-4de9-aa40-94056ec41ba1)

**Comment by ruslanlap** [comment]
Thanks for the detailed report and screenshot!

Tomorrow I’ll take a closer look at your request and try to reproduce the issue on my side to better understand what’s going on.
Sorry for the inconvenience, and thank you for your patience!

    Thank you, I will fix tomorrow

**Comment by ZOXSOCKS** [comment]
This still hasn't worked following your exact steps! I'll have to try do a full, clean reinstall of PowerToys. I will get back to you.

**Comment by IMOrigami** [comment]
I'm encountering the same. It appears the download is installing an older version:

![Image](https://github.com/user-attachments/assets/9af00469-5a7b-4e6b-8c19-8d042748bec8)

**Comment by ruslanlap** [comment]
> I'm encountering the same. It appears the download is installing an older version:
> 
> ![Image](https://github.com/user-attachments/assets/9af00469-5a7b-4e6b-8c19-8d042748bec8)
> 

Ok, sorry for this experience, I will fix it asap

**Comment by ruslanlap** [comment]
> Got it working! Thanks for all your hard work!

Awesome! Thanks a lot !Stay with project)
